let mode="login",cur=null;const $=x=>document.getElementById(x);async function api(u,o={}){let r=await fetch(u,{headers:{"Content-Type":"application/json"},...o}),x=await r.json();if(!r.ok)throw Error(x.error);return x}
function show(id){["home","auth","dash","edit"].forEach(x=>$(x).classList.toggle("hide",x!==id));if(id==="dash")load()}
function auth(){$("abox").innerHTML=mode==="login"?`<h2>Тавтай морил 💖</h2><label>Email<input id="email"></label><label>Нууц үг<input id="pw" type="password"></label><button class="primary" onclick="login()">Нэвтрэх</button>`:`<h2>Бүртгэл үүсгэх</h2><label>Нэр<input id="name"></label><label>Email<input id="email"></label><label>Нууц үг<input id="pw" type="password"></label><button class="primary" onclick="reg()">Бүртгүүлэх</button>`}
async function login(){try{await api("/api/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("pw").value})});show("dash")}catch(e){alert(e.message)}}
async function reg(){try{await api("/api/register",{method:"POST",body:JSON.stringify({name:$("name").value,email:$("email").value,password:$("pw").value})});show("dash")}catch(e){alert(e.message)}}
async function logout(){await api("/api/logout",{method:"POST"});show("home")}
async function load(){try{let a=await api("/api/invitations");$("list").innerHTML=a.length?a.map(x=>`<div class=card><span>${x.type}</span><h3>${esc(x.title)}</h3><p>${x.date||"—"} · ${x.venue||"—"}</p><small>👥 ${x.guests||0} · ✅ ${x.yes_count||0} · 🤔 ${x.maybe_count||0} · ❌ ${x.no_count||0}</small><br><button onclick="edit(${x.id})">Засах</button> <button onclick="navigator.clipboard.writeText(location.origin+'/i/${x.slug}');alert('Link хууллаа')">🔗 Link</button></div>`).join(""):`<div class=card>Одоохондоо урилга алга.</div>`}catch(e){show("auth")}}
function newInv(){cur=null;["title","date","time","venue","message"].forEach(x=>$(x).value="");$("type").value="birthday";$("template").value="classic";preview();$("gs").innerHTML="";show("edit")}
async function edit(id){cur=(await api("/api/invitations")).find(x=>x.id===id);$("title").value=cur.title;$("type").value=cur.type;$("date").value=cur.date||"";$("time").value=cur.time||"";$("venue").value=cur.venue||"";$("message").value=cur.message||"";$("template").value=cur.template||"classic";preview();loadGuests();show("edit")}
function data(){return{title:$("title").value,type:$("type").value,date:$("date").value,time:$("time").value,venue:$("venue").value,message:$("message").value,template:$("template").value}}
async function save(){try{if(cur)await api("/api/invitations/"+cur.id,{method:"PUT",body:JSON.stringify(data())});else{let x=await api("/api/invitations",{method:"POST",body:JSON.stringify(data())});cur=x}alert("Хадгалагдлаа ✨");loadGuests()}catch(e){alert(e.message)}}
function preview(){$("preview").innerHTML=`<div><span>💌 ${$("type").value}</span><h1>${esc($("title").value||"Таны урилга")}</h1><p>${esc($("message").value||"Таныг хүрэлцэн ирэхийг урьж байна.")}</p><p>📅 ${$("date").value||"—"}<br>⏰ ${$("time").value||"—"}<br>📍 ${esc($("venue").value||"—")}</p></div>`}
["title","type","date","time","venue","message","template"].forEach(x=>document.addEventListener("input",e=>e.target.id===x&&preview()))
async function loadGuests(){let a=await api("/api/invitations/"+cur.id+"/guests");$("gs").innerHTML=a.length?a.map(g=>`<div class=guest><input value="${esc(g.name)}" onchange="upg(${g.id},{name:this.value})"><select onchange="upg(${g.id},{status:this.value})"><option value=pending ${g.status==="pending"?"selected":""}>Хариулаагүй</option><option value=yes ${g.status==="yes"?"selected":""}>Ирнэ</option><option value=maybe ${g.status==="maybe"?"selected":""}>Магадгүй</option><option value=no ${g.status==="no"?"selected":""}>Ирэхгүй</option></select><button onclick="delg(${g.id})">🗑</button></div>`).join(""):"<p>Зочин нэмээгүй байна.</p>"}
async function addGuest(){let n=prompt("Зочны нэр:");if(n)await api("/api/invitations/"+cur.id+"/guests",{method:"POST",body:JSON.stringify({name:n})});loadGuests()}
async function upg(id,d){await api("/api/guests/"+id,{method:"PUT",body:JSON.stringify(d)})}async function delg(id){await api("/api/guests/"+id,{method:"DELETE"});loadGuests()}function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
api("/api/me").then(x=>show(x.user?"dash":"home"));